"""Pinecone vector storage and hosted embedding inference for KisanVault.

Embeddings are generated by Pinecone Inference rather than locally. This keeps
SentenceTransformers/PyTorch out of the Render runtime and avoids the memory
pressure that caused the previous deployment to exceed its limit.
"""

import logging
from typing import List, Dict, Any, Optional

from app.config import settings

logger = logging.getLogger(__name__)

_pinecone_client = None
_pinecone_index = None
_pinecone_available = None


def _get_pinecone_client():
    """Create and cache the Pinecone client."""
    global _pinecone_client, _pinecone_available

    if _pinecone_available is False:
        return None

    if _pinecone_client is not None:
        return _pinecone_client

    try:
        from pinecone import Pinecone

        if not settings.PINECONE_API_KEY:
            raise ValueError("PINECONE_API_KEY is not set.")

        _pinecone_client = Pinecone(api_key=settings.PINECONE_API_KEY)
        _pinecone_available = True
        logger.info(
            "Pinecone client ready; hosted embedding model '%s'.",
            settings.PINECONE_EMBEDDING_MODEL,
        )
        return _pinecone_client
    except Exception as e:
        _pinecone_available = False
        logger.warning("Pinecone unavailable — vector search disabled: %s", e)
        return None


def _get_pinecone_index():
    """Return the configured Pinecone index."""
    global _pinecone_index

    if _pinecone_index is not None:
        return _pinecone_index

    client = _get_pinecone_client()
    if client is None:
        return None

    try:
        _pinecone_index = client.Index(settings.PINECONE_INDEX_NAME)
        logger.info("Pinecone index '%s' ready.", settings.PINECONE_INDEX_NAME)
        return _pinecone_index
    except Exception as e:
        logger.warning("Could not open Pinecone index: %s", e)
        return None


def _embed_text(text: str, input_type: str) -> List[float]:
    """Generate a dense embedding using Pinecone's hosted inference model."""
    client = _get_pinecone_client()
    if client is None:
        raise RuntimeError("Pinecone client is unavailable.")

    embeddings = client.inference.embed(
        model=settings.PINECONE_EMBEDDING_MODEL,
        inputs=[text],
        parameters={
            "input_type": input_type,
            "truncate": "END",
            "dimension": settings.PINECONE_EMBEDDING_DIMENSION,
        },
    )

    if not embeddings.data:
        raise RuntimeError("Pinecone returned no embedding.")

    values = embeddings.data[0].values
    expected = settings.PINECONE_EMBEDDING_DIMENSION
    if len(values) != expected:
        raise RuntimeError(
            f"Embedding dimension mismatch: expected {expected}, got {len(values)}."
        )

    return values


def _record_to_text(record: Dict[str, Any], table: str) -> str:
    """Convert any legacy record dict to searchable text."""
    if table == "activities":
        return (
            f"Field: {record.get('field_name', 'N/A')}\n"
            f"Crop: {record.get('crop_name', 'N/A')}\n"
            f"Season: {record.get('season', 'N/A')}\n"
            f"Activity: {record.get('activity_type', 'N/A')}\n"
            f"Description: {record.get('description', 'N/A')}\n"
            f"Date: {record.get('date', 'N/A')}\n"
            f"Quantity: {record.get('quantity', 'N/A')} {record.get('unit', '')}\n"
            f"Cost: {record.get('cost', 'N/A')}\n"
        )
    if table == "expenses":
        return (
            f"Field: {record.get('field_name', 'N/A')}\n"
            f"Crop: {record.get('crop_name', 'N/A')}\n"
            f"Season: {record.get('season', 'N/A')}\n"
            f"Expense Type: {record.get('expense_type', 'N/A')}\n"
            f"Amount: {record.get('amount', 'N/A')}\n"
            f"Description: {record.get('description', 'N/A')}\n"
            f"Date: {record.get('date', 'N/A')}\n"
        )
    if table == "harvests":
        return (
            f"Field: {record.get('field_name', 'N/A')}\n"
            f"Crop: {record.get('crop_name', 'N/A')}\n"
            f"Season: {record.get('season', 'N/A')}\n"
            f"Harvest Date: {record.get('harvest_date', 'N/A')}\n"
            f"Quantity: {record.get('quantity', 'N/A')} {record.get('unit', 'kg')}\n"
            f"Selling Price: {record.get('selling_price', 'N/A')}\n"
            f"Total Revenue: {record.get('total_revenue', 'N/A')}\n"
            f"Quality Notes: {record.get('quality_notes', 'N/A')}\n"
        )
    if table == "crops":
        return (
            f"Field: {record.get('field_name', 'N/A')}\n"
            f"Crop: {record.get('crop_name', 'N/A')}\n"
            f"Season: {record.get('season', 'N/A')}\n"
            f"Sowing Date: {record.get('sowing_date', 'N/A')}\n"
            f"Expected Harvest: {record.get('expected_harvest_date', 'N/A')}\n"
            f"Status: {record.get('status', 'N/A')}\n"
        )
    return str(record)


def embed_and_store(
    record_id: str,
    table: str,
    record_or_text: Any,
    user_id: str,
) -> None:
    """Embed a farm record with Pinecone Inference and store it in Pinecone."""
    try:
        index = _get_pinecone_index()
        if index is None:
            logger.warning("Skipping embed for %s — Pinecone unavailable.", record_id)
            return

        text = (
            record_or_text
            if isinstance(record_or_text, str)
            else _record_to_text(record_or_text, table)
        )
        embedding = _embed_text(text, input_type="passage")

        index.upsert(
            vectors=[
                {
                    "id": record_id,
                    "values": embedding,
                    "metadata": {
                        "record_id": record_id,
                        "table": table,
                        "user_id": user_id,
                        "text": text,
                    },
                }
            ]
        )
        logger.info("Embedded record %s (%s) into Pinecone.", record_id, table)
    except Exception as e:
        logger.error("Failed to embed record %s: %s", record_id, e)


def query_similar(
    query_text: str,
    n_results: int = 5,
    where: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    """Search Pinecone using a Pinecone-hosted query embedding."""
    try:
        index = _get_pinecone_index()
        if index is None:
            return []

        query_embedding = _embed_text(query_text, input_type="query")

        kwargs = {
            "vector": query_embedding,
            "top_k": n_results,
            "include_metadata": True,
        }
        if where:
            kwargs["filter"] = {k: {"$eq": v} for k, v in where.items()}

        results = index.query(**kwargs)

        hits = []
        if results and results.matches:
            for match in results.matches:
                metadata = match.metadata or {}
                hits.append(
                    {
                        "record_id": metadata.get("record_id", match.id),
                        "table": metadata.get("table", "unknown"),
                        "text_preview": metadata.get("text", "")[:300],
                        "distance": match.score,
                    }
                )
        return hits
    except Exception as e:
        logger.error("Pinecone query failed: %s", e)
        return []


def delete_record(record_id: str, user_id: Optional[str] = None) -> None:
    """Remove a record from Pinecone when deleted from the database."""
    try:
        index = _get_pinecone_index()
        if index is None:
            return

        if user_id:
            index.delete(
                filter={
                    "record_id": {"$eq": record_id},
                    "user_id": {"$eq": user_id},
                }
            )
        else:
            index.delete(ids=[record_id])

        logger.info("Deleted record %s from Pinecone.", record_id)
    except Exception as e:
        logger.warning("Could not delete %s from Pinecone: %s", record_id, e)


def collection_count() -> int:
    """Return the number of vectors in the Pinecone index."""
    try:
        index = _get_pinecone_index()
        if index is not None:
            stats = index.describe_index_stats()
            return stats.total_vector_count
        return 0
    except Exception as e:
        logger.warning("Could not get collection count from Pinecone: %s", e)
        return 0
