"""Unified Farm Record

Revision ID: cf3820f66b7e
Revises: 
Create Date: 2026-09-20 20:51:14.903641
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf3820f66b7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops')
    op.drop_table('expenses')
    op.drop_table('harvests')
    op.drop_table('fields')
    op.drop_table('activities')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('activities',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=True),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('area_acres', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvests',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('harvest_date', sa.DATE(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quality_notes', sa.TEXT(), nullable=True),
    sa.Column('selling_price', sa.FLOAT(), nullable=True),
    sa.Column('total_revenue', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=True),
    sa.Column('expense_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('season', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sowing_date', sa.DATE(), nullable=True),
    sa.Column('expected_harvest_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
