"""Unified Farm Record

Revision ID: cf3820f66b7e
Revises: 
Create Date: 2026-09-20 20:51:14.903641
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf3820f66b7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table('farm_records',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('expense_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('harvest_quantity', sa.Float(), nullable=True),
    sa.Column('harvest_unit', sa.String(length=50), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_records_id'), 'farm_records', ['id'], unique=False)
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'crops' in tables:
        op.drop_table('crops')
    if 'expenses' in tables:
        op.drop_table('expenses')
    if 'harvests' in tables:
        op.drop_table('harvests')
    if 'fields' in tables:
        op.drop_table('fields')
    if 'activities' in tables:
        op.drop_table('activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_records_id'), table_name='farm_records')
    op.drop_table('farm_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    op.create_table('activities',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=True),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('area_acres', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvests',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('harvest_date', sa.DATE(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quality_notes', sa.TEXT(), nullable=True),
    sa.Column('selling_price', sa.FLOAT(), nullable=True),
    sa.Column('total_revenue', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_id', sa.NUMERIC(), nullable=True),
    sa.Column('expense_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('field_id', sa.NUMERIC(), nullable=False),
    sa.Column('crop_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('season', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sowing_date', sa.DATE(), nullable=True),
    sa.Column('expected_harvest_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
